In [1]:
import numpy as np

In [4]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [7]:
v_add = v1+v2
v_sub = v1-v2

print(v_add)
print(v_sub)

[5 7 9]
[-3 -3 -3]


In [8]:
scale_v1 = v1*2
print(scale_v1)

[2 4 6]


In [9]:
print(np.dot(v1,v2))

32


In [11]:
#magnitude 
mag = np.linalg.norm(v1)
print(mag)

3.7416573867739413
